name: ws_build

on: 
  push:
    branches:
      - master
      - devel

jobs:
  workspace-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with: 
          path: workspace
      
      - name: Set up ROS2 workspace
        uses: ichiro-its/ros2-actions/setup@v1.0.0
        with:
          distro: humble
          workspace_dir: workspace
      
      - name: Build the workspace
        uses: ichiro-its/ros2-actions/build@v1.0.0

      - name: Test the workspace
        run:
          source install/setup.bash
          colcon test --return-code-on-tesy-failure 